export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const SET_USERS = 'SET_USERS'
export const SET_USER_MESSAGES = 'SET_USER_MESSAGES'
export const SET_SELECTED_USER = 'SET_SELECTED_USER'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const ADD_REACTION = 'ADD_REACTION'